import type { DefaultTheme } from 'vitepress'

// Auto-generated by scripts/generate-sidebar.mjs. Do not edit manually.
// Generated at: 2026-07-14T11:26:46.930Z

export const sidebar: DefaultTheme.Config['sidebar'] = {
  "/": [
    {
      "text": "Root",
      "collapsed": false,
      "items": [
        {
          "text": "Api Examples",
          "link": "/api-examples"
        },
        {
          "text": "Markdown Examples",
          "link": "/markdown-examples"
        },
        {
          "text": "README",
          "link": "/README"
        }
      ]
    }
  ],
  "/android/": [
    {
      "text": "Android",
      "collapsed": false,
      "items": [
        {
          "text": "Coroutine",
          "link": "/android/1.coroutine"
        }
      ]
    }
  ],
  "/ios/": [
    {
      "text": "Ios",
      "collapsed": false,
      "items": [
        {
          "text": "Basic",
          "collapsed": true,
          "items": [
            {
              "text": "Struct Vs Class V1",
              "link": "/ios/basic/1.struct_vs_class_v1"
            },
            {
              "text": "Serial Queue",
              "link": "/ios/basic/11.serial_queue"
            },
            {
              "text": "Concurrent Queue",
              "link": "/ios/basic/12.concurrent_queue"
            },
            {
              "text": "Combine",
              "link": "/ios/basic/13.combine"
            },
            {
              "text": "Async Await",
              "link": "/ios/basic/14.async_await"
            },
            {
              "text": "Task",
              "link": "/ios/basic/15.task"
            },
            {
              "text": "Swift Ui",
              "link": "/ios/basic/16.swift_ui"
            },
            {
              "text": "Render Pipeline",
              "link": "/ios/basic/17.render_pipeline"
            },
            {
              "text": "App Launch Flow",
              "link": "/ios/basic/18.app_launch_flow"
            },
            {
              "text": "Ios Frameworks",
              "link": "/ios/basic/19.ios_frameworks"
            },
            {
              "text": "Struct Vs Class V2",
              "link": "/ios/basic/2.struct_vs_class_v2"
            },
            {
              "text": "Struct Vs Class V3",
              "link": "/ios/basic/3.struct_vs_class_v3"
            },
            {
              "text": "Class Vtable",
              "link": "/ios/basic/4.class_%20vtable"
            },
            {
              "text": "Block",
              "link": "/ios/basic/5.block"
            },
            {
              "text": "Ios Memory",
              "link": "/ios/basic/6.ios_memory"
            },
            {
              "text": "Auto Release Pool",
              "link": "/ios/basic/7.auto_release_pool"
            }
          ]
        },
        {
          "text": "Core",
          "collapsed": true,
          "items": [
            {
              "text": "Dyld",
              "link": "/ios/core/1.dyld"
            },
            {
              "text": "编译流程",
              "link": "/ios/core/2.%E7%BC%96%E8%AF%91%E6%B5%81%E7%A8%8B"
            },
            {
              "text": "函数派发",
              "link": "/ios/core/3.%E5%87%BD%E6%95%B0%E6%B4%BE%E5%8F%91"
            },
            {
              "text": "Runtime",
              "link": "/ios/core/4.runtime"
            },
            {
              "text": "Runloop",
              "link": "/ios/core/5.runloop"
            },
            {
              "text": "Gcd",
              "link": "/ios/core/6.gcd"
            },
            {
              "text": "ASLR",
              "link": "/ios/core/7.ASLR"
            },
            {
              "text": "Crash Collect",
              "link": "/ios/core/8.crash_collect"
            }
          ]
        },
        {
          "text": "Functions",
          "collapsed": true,
          "items": [
            {
              "text": "Network Alamofire",
              "link": "/ios/functions/1.network-alamofire"
            },
            {
              "text": "Network Moya",
              "link": "/ios/functions/2.network-moya"
            },
            {
              "text": "Image Kingfisher",
              "link": "/ios/functions/3.image-kingfisher"
            },
            {
              "text": "Realm",
              "link": "/ios/functions/4.realm"
            },
            {
              "text": "Llm Stream Chat",
              "link": "/ios/functions/5.llm_stream_chat"
            },
            {
              "text": "Push Notification",
              "link": "/ios/functions/6.push_notification"
            },
            {
              "text": "Webview",
              "link": "/ios/functions/7.webview"
            },
            {
              "text": "Large Image Render",
              "link": "/ios/functions/8.large-image-render"
            },
            {
              "text": "Objectbox",
              "link": "/ios/functions/9.objectbox"
            }
          ]
        },
        {
          "text": "Graphics",
          "collapsed": true,
          "items": [
            {
              "text": "Open Gl",
              "link": "/ios/graphics/open_gl"
            }
          ]
        },
        {
          "text": "Hardware",
          "collapsed": true,
          "items": [
            {
              "text": "Applet",
              "link": "/ios/hardware/applet"
            },
            {
              "text": "Card Type",
              "link": "/ios/hardware/card_type"
            },
            {
              "text": "Carplay",
              "link": "/ios/hardware/Carplay"
            },
            {
              "text": "SE存储区域",
              "link": "/ios/hardware/SE%E5%AD%98%E5%82%A8%E5%8C%BA%E5%9F%9F"
            },
            {
              "text": "车联网联盟",
              "link": "/ios/hardware/%E8%BD%A6%E8%81%94%E7%BD%91%E8%81%94%E7%9B%9F"
            },
            {
              "text": "BLE",
              "collapsed": true,
              "items": [
                {
                  "text": "BLE",
                  "link": "/ios/hardware/BLE/BLE"
                },
                {
                  "text": "RFCOMM",
                  "link": "/ios/hardware/BLE/RFCOMM"
                },
                {
                  "text": "术语",
                  "link": "/ios/hardware/BLE/%E6%9C%AF%E8%AF%AD"
                }
              ]
            },
            {
              "text": "CC",
              "collapsed": true,
              "items": [
                {
                  "text": "Deps",
                  "link": "/ios/hardware/CC/Deps"
                },
                {
                  "text": "MGU",
                  "link": "/ios/hardware/CC/MGU"
                },
                {
                  "text": "SDIP",
                  "link": "/ios/hardware/CC/SDIP"
                },
                {
                  "text": "VehicleInfo",
                  "link": "/ios/hardware/CC/VehicleInfo"
                }
              ]
            },
            {
              "text": "EA",
              "collapsed": true,
              "items": [
                {
                  "text": "Iap2",
                  "link": "/ios/hardware/EA/iap2"
                }
              ]
            }
          ]
        }
      ]
    }
  ],
  "/js/": [
    {
      "text": "Js",
      "collapsed": false,
      "items": [
        {
          "text": "Mcp Transport Architecture",
          "link": "/js/mcp-transport-architecture"
        }
      ]
    }
  ],
  "/flutter/": [
    {
      "text": "Flutter",
      "collapsed": false,
      "items": [
        {
          "text": "Flutter Bloc",
          "link": "/flutter/1.flutter_bloc"
        },
        {
          "text": "Flutter Restorable",
          "link": "/flutter/10.flutter_restorable"
        },
        {
          "text": "股票绘制",
          "link": "/flutter/11.%E8%82%A1%E7%A5%A8%E7%BB%98%E5%88%B6"
        },
        {
          "text": "Fl Chart",
          "link": "/flutter/12.fl_chart"
        },
        {
          "text": "Offf Screen Capture",
          "link": "/flutter/13.offf_screen_capture"
        },
        {
          "text": "Hive",
          "link": "/flutter/14.hive"
        },
        {
          "text": "Flutter Paint Widgets",
          "link": "/flutter/15.flutter_paint_widgets"
        },
        {
          "text": "Drift",
          "link": "/flutter/17.drift"
        },
        {
          "text": "Stream Chat",
          "link": "/flutter/18.stream_chat"
        },
        {
          "text": "Agentivity Ag Ui",
          "link": "/flutter/19.agentivity_ag_ui"
        },
        {
          "text": "River Pod",
          "link": "/flutter/2.river_pod"
        },
        {
          "text": "Flutter Apm Enhancement",
          "link": "/flutter/20.flutter_apm_enhancement"
        },
        {
          "text": "Flutter Event Loop",
          "link": "/flutter/3.flutter_event_loop"
        },
        {
          "text": "Flutter Zone",
          "link": "/flutter/4.flutter_zone"
        },
        {
          "text": "Flutter Communication",
          "link": "/flutter/5.flutter_communication"
        },
        {
          "text": "Flutter Three Tree",
          "link": "/flutter/6.flutter_three_tree"
        },
        {
          "text": "Flutter Render Pipeline",
          "link": "/flutter/7.flutter_render_pipeline"
        },
        {
          "text": "Flutter Engine",
          "link": "/flutter/8.flutter_engine"
        },
        {
          "text": "Flutter Upgrade",
          "link": "/flutter/9.flutter_upgrade"
        }
      ]
    }
  ],
  "/ai-agent/": [
    {
      "text": "Ai Agent",
      "collapsed": false,
      "items": [
        {
          "text": "Prompt",
          "link": "/ai-agent/1.prompt"
        }
      ]
    }
  ],
  "/llvm/": [
    {
      "text": "Llvm",
      "collapsed": false,
      "items": [
        {
          "text": "Ollama简介",
          "link": "/llvm/1.ollama%E7%AE%80%E4%BB%8B"
        },
        {
          "text": "Ollama工作流程",
          "link": "/llvm/2.ollama%E5%B7%A5%E4%BD%9C%E6%B5%81%E7%A8%8B"
        },
        {
          "text": "Llama Server",
          "link": "/llvm/3.llama-server"
        },
        {
          "text": "Anythingllvm",
          "link": "/llvm/4.anythingllvm"
        }
      ]
    }
  ],
  "/todo/": [
    {
      "text": "Todo",
      "collapsed": false,
      "items": [
        {
          "text": "麻将",
          "link": "/todo/1.%E9%BA%BB%E5%B0%86"
        },
        {
          "text": "TODO LIST",
          "link": "/todo/TODO_LIST"
        }
      ]
    }
  ]
}
