import type { DefaultTheme } from 'vitepress'

// Auto-generated by scripts/generate-sidebar.mjs. Do not edit manually.
// Generated at: 2026-08-14T05:30:32.785Z

export const sidebar: DefaultTheme.Config['sidebar'] = {
  "/": [
    {
      "text": "Root",
      "collapsed": false,
      "items": [
        {
          "text": "README",
          "link": "/README"
        }
      ]
    }
  ],
  "/android/": [
    {
      "text": "Android",
      "collapsed": false,
      "items": [
        {
          "text": "Coroutine",
          "link": "/android/1.coroutine"
        }
      ]
    }
  ],
  "/ios/": [
    {
      "text": "Ios",
      "collapsed": false,
      "items": [
        {
          "text": "Architecture",
          "collapsed": true,
          "items": [
            {
              "text": "DIInject",
              "link": "/ios/architecture/DIInject"
            },
            {
              "text": "Modules",
              "link": "/ios/architecture/Modules"
            },
            {
              "text": "Network",
              "link": "/ios/architecture/Network"
            },
            {
              "text": "Router",
              "link": "/ios/architecture/Router"
            }
          ]
        },
        {
          "text": "Av",
          "collapsed": true,
          "items": [
            {
              "text": "Ffmpeg",
              "link": "/ios/av/1.ffmpeg"
            },
            {
              "text": "Av Foundation",
              "link": "/ios/av/2.av_foundation"
            },
            {
              "text": "Audio Process",
              "link": "/ios/av/3.audio_process"
            },
            {
              "text": "Av Audio",
              "link": "/ios/av/4.av_audio"
            },
            {
              "text": "IOS高性能计算",
              "link": "/ios/av/5.iOS%E9%AB%98%E6%80%A7%E8%83%BD%E8%AE%A1%E7%AE%97"
            }
          ]
        },
        {
          "text": "Basic",
          "collapsed": true,
          "items": [
            {
              "text": "Swift",
              "link": "/ios/basic/0.swift"
            },
            {
              "text": "Struct Vs Class V1",
              "link": "/ios/basic/1.struct_vs_class_v1"
            },
            {
              "text": "Serial Queue",
              "link": "/ios/basic/11.serial_queue"
            },
            {
              "text": "Concurrent Queue",
              "link": "/ios/basic/12.concurrent_queue"
            },
            {
              "text": "Combine",
              "link": "/ios/basic/13.combine"
            },
            {
              "text": "Lock",
              "link": "/ios/basic/13.lock"
            },
            {
              "text": "Async Await",
              "link": "/ios/basic/14.async_await"
            },
            {
              "text": "Task",
              "link": "/ios/basic/15.task"
            },
            {
              "text": "Swift Ui",
              "link": "/ios/basic/16.swift_ui"
            },
            {
              "text": "Render Pipeline",
              "link": "/ios/basic/17.render_pipeline"
            },
            {
              "text": "App Launch Flow",
              "link": "/ios/basic/18.app_launch_flow"
            },
            {
              "text": "Ios Frameworks",
              "link": "/ios/basic/19.ios_frameworks"
            },
            {
              "text": "Struct Vs Class V2",
              "link": "/ios/basic/2.struct_vs_class_v2"
            },
            {
              "text": "Swift Macro",
              "link": "/ios/basic/20.swift_macro"
            },
            {
              "text": "Swift Animation",
              "link": "/ios/basic/21.swift_animation"
            },
            {
              "text": "Viper",
              "link": "/ios/basic/22.viper"
            },
            {
              "text": "Background Task",
              "link": "/ios/basic/23.background_task"
            },
            {
              "text": "Design Pattern",
              "link": "/ios/basic/24.design_pattern"
            },
            {
              "text": "Swift Ui Test",
              "link": "/ios/basic/25.swift_ui_test"
            },
            {
              "text": "App Kit",
              "link": "/ios/basic/26.app_kit"
            },
            {
              "text": "Struct Vs Class V3",
              "link": "/ios/basic/3.struct_vs_class_v3"
            },
            {
              "text": "Class Vtable",
              "link": "/ios/basic/4.class_vtable"
            },
            {
              "text": "Block",
              "link": "/ios/basic/5.block"
            },
            {
              "text": "Ios Memory",
              "link": "/ios/basic/6.ios_memory"
            },
            {
              "text": "Auto Release Pool",
              "link": "/ios/basic/7.auto_release_pool"
            }
          ]
        },
        {
          "text": "Core",
          "collapsed": true,
          "items": [
            {
              "text": "Dyld",
              "link": "/ios/core/1.dyld"
            },
            {
              "text": "Upload App Store",
              "link": "/ios/core/10.upload_app_store"
            },
            {
              "text": "Code Sign",
              "link": "/ios/core/11.code_sign"
            },
            {
              "text": "编译流程",
              "link": "/ios/core/2.%E7%BC%96%E8%AF%91%E6%B5%81%E7%A8%8B"
            },
            {
              "text": "函数派发",
              "link": "/ios/core/3.%E5%87%BD%E6%95%B0%E6%B4%BE%E5%8F%91"
            },
            {
              "text": "Runtime",
              "link": "/ios/core/4.runtime"
            },
            {
              "text": "Runloop",
              "link": "/ios/core/5.runloop"
            },
            {
              "text": "Gcd",
              "link": "/ios/core/6.gcd"
            },
            {
              "text": "ASLR",
              "link": "/ios/core/7.ASLR"
            },
            {
              "text": "Crash Collect",
              "link": "/ios/core/8.crash_collect"
            },
            {
              "text": "Apm",
              "link": "/ios/core/9.apm"
            }
          ]
        },
        {
          "text": "Functions",
          "collapsed": true,
          "items": [
            {
              "text": "Network Alamofire",
              "link": "/ios/functions/1.network-alamofire"
            },
            {
              "text": "Ios Rich Text",
              "link": "/ios/functions/11.ios_rich_text"
            },
            {
              "text": "Animations",
              "link": "/ios/functions/12.animations"
            },
            {
              "text": "Accessory Setupkit",
              "link": "/ios/functions/13.accessory_setupkit"
            },
            {
              "text": "Swift Data",
              "link": "/ios/functions/15.swift_data"
            },
            {
              "text": "Tiercel Download",
              "link": "/ios/functions/16.Tiercel_download"
            },
            {
              "text": "Core Motion",
              "link": "/ios/functions/17.core_motion"
            },
            {
              "text": "Network Moya",
              "link": "/ios/functions/2.network-moya"
            },
            {
              "text": "Image Kingfisher",
              "link": "/ios/functions/3.image-kingfisher"
            },
            {
              "text": "Realm",
              "link": "/ios/functions/4.realm"
            },
            {
              "text": "Llm Stream Chat",
              "link": "/ios/functions/5.llm_stream_chat"
            },
            {
              "text": "Push Notification",
              "link": "/ios/functions/6.push_notification"
            },
            {
              "text": "Webview",
              "link": "/ios/functions/7.webview"
            },
            {
              "text": "Large Image Render",
              "link": "/ios/functions/8.large-image-render"
            },
            {
              "text": "Objectbox",
              "link": "/ios/functions/9.objectbox"
            }
          ]
        },
        {
          "text": "Graphics",
          "collapsed": true,
          "items": [
            {
              "text": "Core Image",
              "link": "/ios/graphics/core_image"
            },
            {
              "text": "GameplayKit",
              "link": "/ios/graphics/GameplayKit"
            },
            {
              "text": "Open Gl",
              "link": "/ios/graphics/open_gl"
            },
            {
              "text": "Spritekit",
              "link": "/ios/graphics/spritekit"
            }
          ]
        },
        {
          "text": "Ito",
          "collapsed": true,
          "items": [
            {
              "text": "Applet",
              "link": "/ios/ito/Applet"
            },
            {
              "text": "Carkey",
              "link": "/ios/ito/Carkey"
            },
            {
              "text": "Carplay",
              "link": "/ios/ito/Carplay"
            },
            {
              "text": "CCC",
              "link": "/ios/ito/CCC"
            },
            {
              "text": "SE",
              "link": "/ios/ito/SE"
            },
            {
              "text": "BLE",
              "collapsed": true,
              "items": [
                {
                  "text": "BLE",
                  "link": "/ios/ito/BLE/1.BLE"
                },
                {
                  "text": "L2CAP",
                  "link": "/ios/ito/BLE/2.L2CAP"
                },
                {
                  "text": "L2CAP COC",
                  "link": "/ios/ito/BLE/3.L2CAP-COC"
                },
                {
                  "text": "L2CAP PSM",
                  "link": "/ios/ito/BLE/4.L2CAP-PSM"
                },
                {
                  "text": "RFCOMM",
                  "link": "/ios/ito/BLE/6.RFCOMM"
                }
              ]
            },
            {
              "text": "DK",
              "collapsed": true,
              "items": [
                {
                  "text": "DK简介",
                  "link": "/ios/ito/DK/1.DK%E7%AE%80%E4%BB%8B"
                },
                {
                  "text": "CCC规范",
                  "link": "/ios/ito/DK/2.CCC%E8%A7%84%E8%8C%83"
                },
                {
                  "text": "ICCE规范",
                  "link": "/ios/ito/DK/3.ICCE%E8%A7%84%E8%8C%83"
                }
              ]
            },
            {
              "text": "EA",
              "collapsed": true,
              "items": [
                {
                  "text": "EA",
                  "link": "/ios/ito/EA/EA"
                }
              ]
            },
            {
              "text": "Network",
              "collapsed": true,
              "items": [
                {
                  "text": "Bonjour",
                  "link": "/ios/ito/Network/Bonjour"
                },
                {
                  "text": "CFNetwork",
                  "link": "/ios/ito/Network/CFNetwork"
                },
                {
                  "text": "Network",
                  "link": "/ios/ito/Network/Network"
                }
              ]
            },
            {
              "text": "NFC",
              "collapsed": true,
              "items": [
                {
                  "text": "CoreNFC",
                  "link": "/ios/ito/NFC/CoreNFC"
                },
                {
                  "text": "HCE",
                  "link": "/ios/ito/NFC/HCE"
                }
              ]
            },
            {
              "text": "UWB",
              "collapsed": true,
              "items": [
                {
                  "text": "NearbyInteraction",
                  "link": "/ios/ito/UWB/NearbyInteraction"
                }
              ]
            }
          ]
        }
      ]
    }
  ],
  "/tools/": [
    {
      "text": "Tools",
      "collapsed": false,
      "items": [
        {
          "text": "Brew",
          "link": "/tools/brew"
        }
      ]
    }
  ],
  "/js/": [
    {
      "text": "Js",
      "collapsed": false,
      "items": [
        {
          "text": "Mcp Transport Architecture",
          "link": "/js/mcp-transport-architecture"
        }
      ]
    }
  ],
  "/flutter/": [
    {
      "text": "Flutter",
      "collapsed": false,
      "items": [
        {
          "text": "Flutter Bloc",
          "link": "/flutter/1.flutter_bloc"
        },
        {
          "text": "Flutter Restorable",
          "link": "/flutter/10.flutter_restorable"
        },
        {
          "text": "Stock Draw",
          "link": "/flutter/11.stock_draw"
        },
        {
          "text": "Fl Chart",
          "link": "/flutter/12.fl_chart"
        },
        {
          "text": "Off Screen Capture",
          "link": "/flutter/13.off_screen_capture"
        },
        {
          "text": "Hive",
          "link": "/flutter/14.hive"
        },
        {
          "text": "Flutter Paint Widgets",
          "link": "/flutter/15.flutter_paint_widgets"
        },
        {
          "text": "Drift",
          "link": "/flutter/17.drift"
        },
        {
          "text": "Stream Chat",
          "link": "/flutter/18.stream_chat"
        },
        {
          "text": "Agentivity Ag Ui",
          "link": "/flutter/19.agentivity_ag_ui"
        },
        {
          "text": "River Pod",
          "link": "/flutter/2.river_pod"
        },
        {
          "text": "Flutter Apm Enhancement",
          "link": "/flutter/20.flutter_apm_enhancement"
        },
        {
          "text": "Flutter Event Loop",
          "link": "/flutter/3.flutter_event_loop"
        },
        {
          "text": "Flutter Zone",
          "link": "/flutter/4.flutter_zone"
        },
        {
          "text": "Flutter Communication",
          "link": "/flutter/5.flutter_communication"
        },
        {
          "text": "Flutter Three Tree",
          "link": "/flutter/6.flutter_three_tree"
        },
        {
          "text": "Flutter Render Pipeline",
          "link": "/flutter/7.flutter_render_pipeline"
        },
        {
          "text": "Flutter Engine",
          "link": "/flutter/8.flutter_engine"
        },
        {
          "text": "Flutter Upgrade",
          "link": "/flutter/9.flutter_upgrade"
        }
      ]
    }
  ],
  "/ai-agent/": [
    {
      "text": "Ai Agent",
      "collapsed": false,
      "items": [
        {
          "text": "Prompt",
          "link": "/ai-agent/1.prompt"
        }
      ]
    }
  ],
  "/llm/": [
    {
      "text": "Llm",
      "collapsed": false,
      "items": [
        {
          "text": "Agent",
          "link": "/llm/Agent"
        },
        {
          "text": "Embedding",
          "link": "/llm/Embedding"
        },
        {
          "text": "Memory",
          "link": "/llm/Memory"
        },
        {
          "text": "Prompt",
          "link": "/llm/Prompt"
        },
        {
          "text": "RAG",
          "link": "/llm/RAG"
        },
        {
          "text": "Token",
          "link": "/llm/Token"
        },
        {
          "text": "Transform",
          "link": "/llm/Transform"
        },
        {
          "text": "Thirdparty",
          "collapsed": true,
          "items": [
            {
              "text": "Mobile Rag Engine",
              "link": "/llm/thirdparty/mobile_rag_engine"
            }
          ]
        },
        {
          "text": "Tools",
          "collapsed": true,
          "items": [
            {
              "text": "Ollama简介",
              "link": "/llm/tools/1.ollama%E7%AE%80%E4%BB%8B"
            },
            {
              "text": "Ollama工作流程",
              "link": "/llm/tools/2.ollama%E5%B7%A5%E4%BD%9C%E6%B5%81%E7%A8%8B"
            },
            {
              "text": "Llama Server",
              "link": "/llm/tools/3.llama-server"
            },
            {
              "text": "Anythingllm",
              "link": "/llm/tools/4.anythingllm"
            }
          ]
        }
      ]
    }
  ],
  "/security/": [
    {
      "text": "Security",
      "collapsed": false,
      "items": [
        {
          "text": "Brand",
          "link": "/security/brand"
        },
        {
          "text": "ECC",
          "link": "/security/ECC"
        },
        {
          "text": "Hash",
          "link": "/security/hash"
        },
        {
          "text": "Secrets",
          "link": "/security/secrets"
        },
        {
          "text": "Tee",
          "link": "/security/tee"
        },
        {
          "text": "Vault",
          "link": "/security/vault"
        },
        {
          "text": "证书管理",
          "link": "/security/%E8%AF%81%E4%B9%A6%E7%AE%A1%E7%90%86"
        },
        {
          "text": "防重放篡改",
          "link": "/security/%E9%98%B2%E9%87%8D%E6%94%BE%E7%AF%A1%E6%94%B9"
        }
      ]
    }
  ],
  "/usefullinks/": [
    {
      "text": "Usefullinks",
      "collapsed": false,
      "items": [
        {
          "text": "Usefullinks",
          "link": "/usefullinks/usefullinks"
        }
      ]
    }
  ],
  "/web/": [
    {
      "text": "Web",
      "collapsed": false,
      "items": [
        {
          "text": "Html",
          "link": "/web/1.html"
        }
      ]
    }
  ]
}

export const nav: DefaultTheme.Config['nav'] = [
  {
    "text": "首页",
    "link": "/"
  },
  {
    "text": "AI Agent",
    "link": "/ai-agent/1.prompt"
  },
  {
    "text": "Android",
    "link": "/android/1.coroutine"
  },
  {
    "text": "Flutter",
    "link": "/flutter/1.flutter_bloc"
  },
  {
    "text": "iOS",
    "link": "/ios/basic/1.struct_vs_class_v1"
  },
  {
    "text": "LLM",
    "link": "/llm/tools/1.ollama%E7%AE%80%E4%BB%8B"
  },
  {
    "text": "JS",
    "link": "/js/mcp-transport-architecture"
  },
  {
    "text": "Security",
    "link": "/security/ECC"
  },
  {
    "text": "Tools",
    "link": "/tools/brew"
  },
  {
    "text": "Useful Links",
    "link": "/usefullinks/usefullinks"
  }
]
