import type { DefaultTheme } from 'vitepress'

// Auto-generated by scripts/generate-sidebar.mjs. Do not edit manually.
// Generated at: 2026-06-16T23:43:12.191Z

export const sidebar: DefaultTheme.Config['sidebar'] = {
  "/": [
    {
      "text": "Root",
      "collapsed": false,
      "items": [
        {
          "text": "Api Examples",
          "link": "/api-examples"
        },
        {
          "text": "Markdown Examples",
          "link": "/markdown-examples"
        },
        {
          "text": "TODO LIST",
          "link": "/TODO_LIST"
        }
      ]
    }
  ],
  "/android/": [
    {
      "text": "Android",
      "collapsed": false,
      "items": [
        {
          "text": "Coroutine",
          "link": "/android/1.coroutine"
        }
      ]
    }
  ],
  "/ios/": [
    {
      "text": "Ios",
      "collapsed": false,
      "items": [
        {
          "text": "Basic",
          "collapsed": true,
          "items": [
            {
              "text": "Struct Vs Class V1",
              "link": "/ios/basic/1.struct_vs_class_v1"
            },
            {
              "text": "Gcd",
              "link": "/ios/basic/10.gcd"
            },
            {
              "text": "Serial Queue",
              "link": "/ios/basic/11.serial_queue"
            },
            {
              "text": "Concurrent Queue",
              "link": "/ios/basic/12.concurrent_queue"
            },
            {
              "text": "Combine",
              "link": "/ios/basic/13.combine"
            },
            {
              "text": "Async Await",
              "link": "/ios/basic/14.async_await"
            },
            {
              "text": "Task",
              "link": "/ios/basic/15.task"
            },
            {
              "text": "Swift Ui",
              "link": "/ios/basic/16.swift_ui"
            },
            {
              "text": "Struct Vs Class V2",
              "link": "/ios/basic/2.struct_vs_class_v2"
            },
            {
              "text": "Struct Vs Class V3",
              "link": "/ios/basic/3.struct_vs_class_v3"
            },
            {
              "text": "Class Vtable",
              "link": "/ios/basic/4.class_%20vtable"
            },
            {
              "text": "Block",
              "link": "/ios/basic/5.block"
            },
            {
              "text": "Ios Memory",
              "link": "/ios/basic/6.ios_memory"
            },
            {
              "text": "Auto Release Pool",
              "link": "/ios/basic/7.auto_release_pool"
            },
            {
              "text": "ASLR",
              "link": "/ios/basic/8.ASLR"
            },
            {
              "text": "Runloop",
              "link": "/ios/basic/9.runloop"
            },
            {
              "text": "Hardware",
              "collapsed": true,
              "items": [
                {
                  "text": "Applet",
                  "link": "/ios/basic/hardware/applet"
                }
              ]
            }
          ]
        },
        {
          "text": "Features",
          "collapsed": true,
          "items": [
            {
              "text": "Llm Stream Chat",
              "link": "/ios/features/llm_stream_chat"
            },
            {
              "text": "Push Notification",
              "link": "/ios/features/push_notification"
            },
            {
              "text": "Webview",
              "link": "/ios/features/webview"
            }
          ]
        },
        {
          "text": "Graphics",
          "collapsed": true,
          "items": [
            {
              "text": "Open Gl",
              "link": "/ios/graphics/open_gl"
            }
          ]
        },
        {
          "text": "Hardware",
          "collapsed": true,
          "items": [
            {
              "text": "Applet",
              "link": "/ios/hardware/applet"
            },
            {
              "text": "Card Type",
              "link": "/ios/hardware/card_type"
            },
            {
              "text": "Carplay",
              "link": "/ios/hardware/Carplay"
            },
            {
              "text": "SE存储区域",
              "link": "/ios/hardware/SE%E5%AD%98%E5%82%A8%E5%8C%BA%E5%9F%9F"
            },
            {
              "text": "车联网联盟",
              "link": "/ios/hardware/%E8%BD%A6%E8%81%94%E7%BD%91%E8%81%94%E7%9B%9F"
            },
            {
              "text": "BLE",
              "collapsed": true,
              "items": [
                {
                  "text": "BLE",
                  "link": "/ios/hardware/BLE/BLE"
                },
                {
                  "text": "RFCOMM",
                  "link": "/ios/hardware/BLE/RFCOMM"
                },
                {
                  "text": "术语",
                  "link": "/ios/hardware/BLE/%E6%9C%AF%E8%AF%AD"
                }
              ]
            },
            {
              "text": "CC",
              "collapsed": true,
              "items": [
                {
                  "text": "Deps",
                  "link": "/ios/hardware/CC/Deps"
                },
                {
                  "text": "MGU",
                  "link": "/ios/hardware/CC/MGU"
                },
                {
                  "text": "SDIP",
                  "link": "/ios/hardware/CC/SDIP"
                },
                {
                  "text": "VehicleInfo",
                  "link": "/ios/hardware/CC/VehicleInfo"
                }
              ]
            },
            {
              "text": "EA",
              "collapsed": true,
              "items": [
                {
                  "text": "Iap2",
                  "link": "/ios/hardware/EA/iap2"
                }
              ]
            }
          ]
        }
      ]
    }
  ],
  "/flutter/": [
    {
      "text": "Flutter",
      "collapsed": false,
      "items": [
        {
          "text": "Flutter Bloc",
          "link": "/flutter/1.flutter_bloc"
        },
        {
          "text": "River Pod",
          "link": "/flutter/2.river_pod"
        },
        {
          "text": "Flutter Event Loop",
          "link": "/flutter/3.flutter_event_loop"
        },
        {
          "text": "Flutter Zone",
          "link": "/flutter/4.flutter_zone"
        },
        {
          "text": "Flutter Communication",
          "link": "/flutter/5.flutter_communication"
        },
        {
          "text": "Flutter Three Tree",
          "link": "/flutter/6.flutter_three_tree"
        },
        {
          "text": "Flutter Render Pipeline",
          "link": "/flutter/7.flutter_render_pipeline"
        },
        {
          "text": "Flutter Engine",
          "link": "/flutter/8.flutter_engine"
        },
        {
          "text": "Flutter Upgrade",
          "link": "/flutter/9.flutter_upgrade"
        }
      ]
    }
  ]
}
